### PR TITLE
Jupyter demo

### PR DESCRIPTION
**Pull request by ttimbers**
Have a draft of my jupyter demo done that can be run locally.

### CODE REVIEW

**Comment by ttimbers** [comment]
Note - currently this is in R, but I'll make a parallel demo of the exact same notebook in Python so that folks to can see that it works for both. Do you have a preference of which I show at the breakout session? I guess both, but walk through one and then at the end just flip to the other to show that it can be done in both languages?

**Comment by mine-cetinkaya-rundel** [comment]
Somewhat related to your question -- as I was structuring the outline today I had your bits under "automated feedback in python" but that's not entirely true, e.g. this demo is for checking R code in jupyter notebooks (so another R option), which is perfectly fine. Doing both, if time allows, is great. If you had to spend more time on one than the other... R is what a higher proportion of the audience will be more familiar with, but at the same time, we're giving lots of R options anyway so demoing python seems nice too.

**Review by mine-cetinkaya-rundel — COMMENTED** [review]
When I launch the notebook locally I get a popup window with the message `Could not find a kernel matching R. Please select a kernel:`. I can select a kernel or continue without one, but I wasn't expecting that (might be my limited experience with running Jupyter notebooks locally).

**Comment by mine-cetinkaya-rundel** [comment]
This is not a comment on the files in the PR so much, but just something that might be worth mentioning (and maybe you're already planning to): What happens if a student doesn't run the run the cell to setup the automated feedback?

**Comment by mine-cetinkaya-rundel** [comment]
Sorry that my review is a scattershot, lots of my comments do not refer to specific line numbers. I started from scratch to run this, and realized when I got to the `source()` command that I need to not be running this in a Python kernel (duh!) but that requires additional steps. I don't think this will be an issue for the talk itself (the demo is in binder, right?) but we might just want to add some links for local install. Otherwise I think this is good to go!

**Comment by ttimbers** [comment]
> When I launch the notebook locally I get a popup window with the message Could not find a kernel matching R. Please select a kernel:. I can select a kernel or continue without one, but I wasn't expecting that (might be my limited experience with running Jupyter notebooks locally).

That's a bit weird - do you have the R kernel installed? Perhaps it's a version thing? I haven't moved over to 4.0 yet...

> What happens if a student doesn't run the run the cell to setup the automated feedback?

This is a good question! In practice they do, then the tests fail, but the message as to why are a bit cryptic and usually humans (in-person in classroom, or online forum) help them out. This is less of a problem as the course goes on, as we move towards loading all libraries and sourcing files in a cell at the beginning of the notebook, and they learn to ensure they run this, and they learn about "Run all cells" (like knitting a doc from top to bottom). However, in an increasingly remote world, we probably should move to giving more useful messages than this... I could probably include a test to see if the right file has been sourced, and if not, print a useful help message... This is good feedback, thanks!

> Sorry that my review is a scattershot, lots of my comments do not refer to specific line numbers. I started from scratch to run this, and realized when I got to the source() command that I need to not be running this in a Python kernel (duh!) but that requires additional steps. I don't think this will be an issue for the talk itself (the demo is in binder, right?) but we might just want to add some links for local install. Otherwise I think this is good to go!

No problem, all these points are useful. I think I will add docs (perhaps in the main repo README) on 3 ways to interact with this demo (locally, remotely and ephemerally using binder, and using a JupyterHub with persistent storage).

Many thanks for all this!

**Comment by mine-cetinkaya-rundel** [comment]
I didn't have the R kernel installed at the time of writing that first comment about "Could not find kernel", that must have been the issue.

**Comment by ttimbers** [comment]
Update - I have the Python demo done now too. So tomorrow I'll add the installation/usage docs, and add student attempts (part of what I may show in the demo).

**Comment by mine-cetinkaya-rundel** [comment]
Are you able to merge these? I wasn't sure about the permission level.

**Comment by ttimbers** [comment]
I think I can, I just need to deal with conflicts (pull in your changes). I will add the docs first and then merge them.

**Comment by ttimbers** [comment]
I'm just going to merge it for now so it's easier for you to see what I have for my first draft of slides and then I'll send in another PR for the docs.

**Pull request merged**
